---
title: "Forecasting report"
resource_files:
- final.RDS
- aggregated_renested.RDS
- seasonal_plots.RDS
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    storyboard: yes
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(tidyverse)

theme_set(theme_minimal())

final <- readRDS("final.RDS")
seasonal_plots <- readRDS("seasonal_plots.RDS")
aggregated_renested <- readRDS("aggregated_renested.RDS")

```

Forecasting
=======================================================================

Column{.sidebar data-width=250}
----------------------------------------------------------------------

Hello I am a sidebar

```{r}
selectInput(inputId = "mod_selector", 
            label = "Choose a model", 
            choices = final %>% distinct(m_function) %>% as_vector() %>% unname(), 
            selected = "arima")

selectInput(input = "agent_selector", 
            label = "Select a pollutant", 
            choices = final %>% distinct(agent) %>% as_vector() %>% unname)

```


Column {data-width=450}
-----------------------------------------------------------------------

### __Forecast Plot__

```{r}
renderPlot({
  final %>% 
    filter(
      agent == input$agent_selector, 
      m_function == input$mod_selector
    ) %>%
    pluck("fplot",1)
}
)

```

### __Model summary__

```{r}
renderTable({
  final %>% 
    filter(
      agent == input$agent_selector, 
      m_function == input$mod_selector
    ) %>%
    pluck("model",1) %>% 
    pluck("model") %>% 
    sweep::sw_glance() 
})


```



Column {data-width=350}
-----------------------------------------------------------------------


### __Seasonal plot__

```{r}
renderPlot({
  seasonal_plots %>% 
    filter(
      agent == input$agent_selector
    ) %>%
    pluck("seasonal",1)
}
)

```

### __Ridge Plot__

```{r}
aggregated_renested %>% 
  unnest() %>% 
  ggplot(aes(concentration, agent, fill = agent))+
  ggridges::geom_density_ridges(scale = 10, 
                                size = .25,
                                show.legend = FALSE, 
                                alpha = .8)+
  theme_minimal()
```

